---
title: "Research"
---

<!-- One paragraph per paper, newest (top) to oldest (bottom). Probably use a standard APSA style. Include a DOI and hyperlink for all published papers. If you have polished working papers, include links to those as well. -->

My research examines American elections, voter confidence, and how post-election audits are tools to influence voter confidence. A complete list is on [my CV.](cv.pdfelw23;l)

## Published Papers 

Atkeson, Lonna, Yimeng Li, **Sarah Case**, and Miguel Arceo-Miranda. 2026. ["2024 Florida Election Study."](fes-2024.pdf)

## Working Papers

**Case, Sarah**. 2026. "[Behind the Count: How Transparency in Election Audits Can Influence Voter Confidence](behind-the-count.pdf)."

**Sarah Case**, Taylor J. Hill, Caroline Robbins, and Yusaku Horiuchi. 2026. "Review of Conjoint Experiments Within the Discipline and Recommendations for Interpretation." 

Atkeson, Lonna, Yimeng Li, Austin Culter, **Sarah Case**, and Marli Wang Dunietz. 2026. "Election Transparency: Do Postelection Audits Improve Voter Confidence?" [Audit Dashboard](https://www.voterdata.lci.fsu.edu/en).

**Case, Sarah**. 2025. "Did We Move On? Effects of Cross-Pressure Attitudes Between Gender and Partisanship with the #MeToo Movement." 

**Case, Sarah**. 2025. "Layers of Trust: Understanding Voter Confidence Across Electoral Levels in the United States, 2008–2024."

## Presentations and Posters
**Case, Sarah**. 2027. "Behind the Count: How Transparency in Election Audits Can Influence Voter Confidence." Paper accepted for presentation at the Southern Political Science Association Annual Meeting.

Atkeson, Lonna, Yimeng Li, Austin Culter, **Sarah Case**, and Marli Wang Dunietz. 2027. "Election Transparency: Do Postelection Audits Improve Voter Confidence?" Paper accepted for presentation at the Southern Political Science Association Annual Meeting (presenting author).

Atkeson, Lonna, Yimeng Li, Austin Culter, **Sarah Case**, and Marli Wang Dunietz. 2026. "Election Transparency: Do Postelection Audits Improve Voter Confidence?" Poster presented at the Election Center National Conference (presenting author).

**Case, Sarah**. 2026. "Behind the Count: How Transparency in Election Audits Can Influence Voter Confidence." Paper presented at Election Science, Reform, and Administration.

Atkeson, Lonna, Yimeng Li, Austin Culter, **Sarah Case**, and Marli Wang Dunietz. 2026. "Election Transparency: Do Postelection Audits Improve Voter Confidence?" Paper presented at Election Science, Reform, and Administration (presenting author).

**Case, Sarah**. 2026. "Behind the Count: How Transparency in Election Audits Can Influence Voter Confidence." Poster presented at Elections, Public Opinion, and Voting Behavior.

Atkeson, Lonna, Yimeng Li, Austin Culter, **Sarah Case**, and Marli Wang Dunietz. 2026. "Election Transparency: Do Postelection Audits Improve Voter Confidence?" Paper presented at the Southern Political Science Association Annual Meeting (presenting author).

**Case, Sarah**. 2025. "Behind the Count: How Transparency in Election Audits Can Influence Voter Confidence." Poster presented at the Global Public Opinion Inaugural Workshop.

Atkeson, Lonna, Yimeng Li, **Sarah Case**, and Miguel Arceo-Miranda. 2025. "2024 Florida Election Study." Poster presented at Election Science, Reform, and Administration (presenting author).